apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: jupyterhub
    repoURL: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/main/jupyterhub
    targetRevision: 15.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true